# Generated by Django 3.1.6 on 2021-03-27 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=256)),
                ('productimage', models.ImageField(upload_to='newproduct/image/')),
                ('productprice', models.FloatField()),
                ('productdescription', models.CharField(max_length=256)),
                ('productquantity', models.PositiveIntegerField(default=1)),
                ('productaddress', models.CharField(max_length=256)),
                ('hugeproduct', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
